### PR TITLE
Added --pdbid, --url, and --verbose flags.

### PR DESCRIPTION
**Pull request by jchodera**
* Users can now specify '--pdbid pdbid' flag in command-line to retrieve PDB file from RCSB
* Users can also specify '--url URL' to retrieve from custom URL.
* --vebose flag for command-line now prints out some information about what is going on; maybe we can convert this to logging later

### CODE REVIEW

**Comment by jchodera** [comment]
Implements #95

**Comment by jchodera** [comment]
Hm.  There don't seem to be any nosetests of the CLI yet.

**Comment by jchodera** [comment]
I've added some basic nosetests.

**Comment by jchodera** [comment]
These test failures appear to be stochastic and related to sporadic failures to connect to the RCSB.  Perhaps having some form of memoization or caching of PDB files locally could be a way to easily avoid this issue.

**Comment by jchodera** [comment]
This should be good to merge.

**Comment by peastman** [comment]
Looks good.  I'm rerunning the Python 3.3 tests now.

**Comment by peastman** [comment]
I reran them twice, but got errors both times.  I wonder if there's a way we could make this more robust against that sort of failure?

**Comment by rmcgibbo** [comment]
in mdtraj, when we load from a url, i recall that we use a wrapper that
tries up to 3 times or so to grab the url before throwing

**Comment by peastman** [comment]
I don't think all of the errors are caused by network problems.  This, at least, looks like a genuine bug in the code:

```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/pdbfixer/tests/test_cli.py", line 54, in test_url
    run_cli('--url "http://www.rcsb.org/pdb/download/downloadFile.do?fileFormat=pdb&compression=NO&structureId=1LE1"')
  File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/pdbfixer/tests/test_cli.py", line 31, in run_cli
    message += e.output
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by jchodera** [comment]
Good catch, @peastman!

**Comment by peastman** [comment]
Looking at the errors, I notice that test_build_and_simulate has no problems, even though it downloads tons of files.  Most of the problems happen in test_remove_chains.  That one only uses one file... and downloads it ten times!  I wonder if the server is detecting lots of requests for the same URL from the same computer and blocking them?  This could be a DDOS protection mechanism.

Perhaps we should modify that test case to only download the file once and save it to a temporary file.

**Comment by peastman** [comment]
I'll go ahead and merge this, then send a separate PR for the test case.

**Comment by jchodera** [comment]
> Perhaps we should modify that test case to only download the file once and save it to a temporary file.

I think it would be more useful to have `PDBFixer` use memoization or caching, since this would prevent us from having to implement this mechanism in each test one might want to apply to the same PDB.

**Pull request merged**
