### PR TITLE
Simplified examples

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by peastman** [comment]
Alright, why is this not working?  Does it have something to do with the conda build?  Is it running the doctests against the conda installation (which doesn't have the test.pdb file) rather than the repository (which does)?

**Comment by peastman** [comment]
Also, why is it printing the full content of soft.xml to the log?

**Comment by kyleabeauchamp** [comment]
1.  Yes.  We've been installing things inside the python egg.  See, for example, https://github.com/mdtraj/mdtraj/blob/master/mdtraj/tests/test_gro.py#L40

**Comment by kyleabeauchamp** [comment]
Regarding the XML: I have no idea why that keeps getting printed

**Comment by peastman** [comment]
Is there any way to make this work without actually installing the test file as part of the application?

**Comment by jchodera** [comment]
Can you just get by with using [`urlretrieve`](https://docs.python.org/2/library/urllib.html#urllib.urlretrieve) for now?
```python
import urllib
urllib.urlretrieve ("http://www.example.com/songs/mp3.mp3", "mp3.mp3")
```

Otherwise, I'd say we should be distributing data and test files along with the conda package so that we can use it in nosetests as well.

**Comment by jchodera** [comment]
If you want to go the route of distributing data and test files in the package, let us know and we can help set up that structure.

**Comment by kyleabeauchamp** [comment]
As a nosetest, one could skip the test if the PDB file is missing.  For a doctest, I'm not sure if it's as easy.

IMHO, it's not a bad idea to include the necessary test file as part of the application, as it allows us to test conda packages during package building and potentially after installation.

**Comment by jchodera** [comment]
> IMHO, it's not a bad idea to include the necessary test file as part of the application, as it allows us to test conda packages during package building and potentially after installation.

I completely agree with this.

**Comment by peastman** [comment]
> IMHO, it's not a bad idea to include the necessary test file as part of the application

Can we at least put it in the tests directory then?  What do I need to change to make that work?

**Comment by jchodera** [comment]
Sorry for not being able to help earlier. We had a visitor here today. Will
get on this later tonight!

Question: Can we move the tests into pdbfixer with the layout

pdbfixer/tests - nosetests
pdbfixer/tests/data - test datafiles

For other project, this means we can run the nosetests after conda
installation, which is useful for debugging!

**Comment by jchodera** [comment]
See #84

**Pull request closed without merging**
