### PR TITLE
Have travis build pdbfixer-dev conda package and push to binstar

### PR DESCRIPTION
**Pull request by jchodera**
See #75.

Still testing.

### CODE REVIEW

**Comment by jchodera** [comment]
Travis is showing a bunch of nosetest failures.  I can reproduce this on my machine (using the `openmm-dev` conda package).

@peastman : Do the nosetests pass on your machine?  Try this:
```
nosetests pdbfixer --nocapture --verbosity=2 --with-doctest
```

**Comment by jchodera** [comment]
It looks like the current master has a lot of broken nosetests, which are causing the failure.

@peastman: How do you want to handle this?  Do you want to fix the nosetests in a separate PR?

**Comment by peastman** [comment]
It looks like it's building against an out of date version of OpenMM:

    AttributeError: 'Chain' object has no attribute 'id'

**Comment by jchodera** [comment]
So nosetests pass on your machine? Could be that openmm-dev is outdated.

**Comment by kyleabeauchamp** [comment]
The timestamps on openmm-dev packages are different for OSX and linux, not sure if this is an issue or not

**Comment by jchodera** [comment]
> The timestamps on openmm-dev packages are different for OSX and linux, not sure if this is an issue or not

They're built by different jenkins scripts.  But should be +- 1 day of each other.

**Comment by peastman** [comment]
The PR that added the "id" fields was merged into OpenMM over a week ago.

**Comment by jchodera** [comment]
The builds were 5 days ago (`osx`) and 19 hours ago (`linux`) but there were some old files on binstar as well and it is possible that binstar got confused as to which ones to serve up:
https://binstar.org/omnia/openmm-dev/files

I've removed the older files.  Doing more testing.

**Comment by jchodera** [comment]
@peastman : I think we're down to actual errors now.  Can you take a look at the travis output?

**Comment by peastman** [comment]
It looks like that's been broken for ages!  I didn't see it when I ran the tests locally, because it wasn't running the doctests.

@kyleabeauchamp created the problem on May 21 last year (https://github.com/pandegroup/pdbfixer/commit/4a38eb7d9c73c6d709a3d8ce70d29f41b9b9a367) when he added the mandatory chain_id argument, but didn't update the doctest accordingly.  So why hasn't this been failing ever since?  I'm not sure what's going on with that.

**Comment by peastman** [comment]
It also looks like there are some Python 3 issues.  The Python 2.7 build only has that one failure, but the 3.3 build lists a bunch of others.

**Comment by kyleabeauchamp** [comment]
hmm, will take a look. 

Actually, it might make sense to refactor some of the changes that I implemented to use the latest features from openmm

**Comment by jchodera** [comment]
Perhaps doc tests were not being run?

If you want to fix in a separate PR first, let me know.

**Comment by peastman** [comment]
The --with-doctest flag has been included since March of last year, so they should have been.  Let's try to resolve the problems first, then merge this when we get a clean build.

**Comment by jchodera** [comment]
> Let's try to resolve the problems first, then merge this when we get a clean build.

Just to be clear, you are saying you want to resolve the doctest failures in a separate PR first, then merge #77 after you have tests pass on a local machine---is that right?

**Comment by peastman** [comment]
Correct.  Kyle says he's looking into the doctest problem right now.  As for the Python 3 changes, I think they may be related to the recent PR from @mpharrigan.

**Comment by kyleabeauchamp** [comment]
see #78

**Comment by jchodera** [comment]
OK, looks like Python 2.7 passes now!  

I propose we fix the 3.x issues in a separate PR.

**Comment by jchodera** [comment]
We can merge this now.

**Comment by jchodera** [comment]
@peastman Apologies to be a pain, but can we merge this?  Would be good to get this package built so we can use it!

**Comment by peastman** [comment]
The doctest is now fixed, but it's still failing on Python 3.  The PR Kyle just sent did *not* have that problem, so I think it must somehow be caused by your changes.  Also, it seems to have started filling up the log by printing out XML files.  I don't think it did that before.

**Comment by kyleabeauchamp** [comment]
It looks like my PR was not running all of the tests?

```
Ran 11 tests in 9.731s
```

```
Ran 8 tests in 309.949s
```

**Comment by jchodera** [comment]
Ah, got it. Will investigate.

**Comment by peastman** [comment]
It looks to me like travis has *not* actually been running the doctests.  I'm not sure why: it's been specifying the --with-doctest flag.  But nonetheless it appears not to have been running them.  This PR adds a setup.cfg file, and that has caused it to start running them.  And that is where the Python 3 errors are happening.

**Comment by jchodera** [comment]
Can we fix the py3 issues in a separate PR? I know very little about py3...

**Comment by peastman** [comment]
Sure.  It looks like that error isn't actually caused by this PR, just made visible by it.

**Pull request merged**
