### PR TITLE
Can build membranes

### LINKED ISSUE #144: Support embedding in a lipid membrane
This would be a nice feature. We should generate a bunch of large membranes and then trim and remove lipids within a certain distance to the protein. VMD can generate arbitrarily large membranes.

For protein orientation, we should advise users to use files from the OPM database http://opm.phar.umich.edu/ which are aligned to the z-axis and have dummy atoms for the top and bottom of the membrane

### PR DESCRIPTION
**Pull request by peastman**
Fixes #144

### CODE REVIEW

**Comment by peastman** [comment]
Has the OpenMM dev build not gotten rebuilt?  Travis reports that it's installing OpenMM from `omnia/label/dev`, but it's not finding files that were added yesterday.  According to https://anaconda.org/omnia/openmm/files, the last update to the dev build was two days ago.

**Comment by peastman** [comment]
Tagging @jchodera in case you aren't following this repository.

**Comment by jchodera** [comment]
Tagging @lnaden.

Looks like there is an [error in the sphinx docs](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/309839769#L8989-L9013
) for OpenMM causing a build failure from a stray non-ASCII character:
```
! Package inputenc Error: Unicode char ϕ (U+3D5)
(inputenc)                not set up for use with LaTeX.
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9879 ...ing improved sampling of the backbone ϕ
                                                  , \(\psi\) and side-chain ...
? 
! Emergency stop.
 ...                                              
                                                  
l.9879 ...ing improved sampling of the backbone ϕ
                                                  , \(\psi\) and side-chain ...
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on OpenMMUsersGuide.log.
make[5]: *** [OpenMMUsersGuide.pdf] Error 1
make[4]: *** [latexpdf] Error 2
make[3]: *** [sphinx-docs/userguide/latex/OpenMMUsersGuide.pdf] Error 2
make[2]: *** [docs-source/CMakeFiles/sphinxpdf.dir/all] Error 2
make[1]: *** [docs-source/CMakeFiles/sphinxpdf.dir/rule] Error 2
make: *** [sphinxpdf] Error 2
```

**Comment by Lnaden** [comment]
Once the dev version is on conda, this PR's tests can be re-triggered and should pass

**Comment by jchodera** [comment]
I've re-triggered the `dev` package build which can be monitored [here](https://travis-ci.org/omnia-md/conda-dev-recipes).

**Comment by peastman** [comment]
Rerunning the tests now.

**Pull request merged**
