### PR TITLE
Test commit

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by jchodera** [comment]
That seems to have reawakened travis!

**Comment by rmcgibbo** [comment]
Perhaps the Travis-CI is confused because #40 was originally a PR to the repo when it was under a different name.

**Comment by rmcgibbo** [comment]
Perhaps easiest to close #40 and reopen a new PR from the same git branch.

**Comment by mpharrigan** [comment]
It'll probably just work with a new commit to that pr

**Pull request closed without merging**
