### PR TITLE
Updated version number to 1.3

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by jchodera** [comment]
I think you said that we need `openmm >=7.0` features in here, right? So you need to update the dependencies too:
https://github.com/pandegroup/pdbfixer/pull/130/files#diff-2eeaed663bd0d25b7e608891384b7298R77

**Comment by peastman** [comment]
Good point.  Fixed!

**Comment by jchodera** [comment]
You want to cut a new GitHub release, and then I'll update the conda recipe?

**Comment by peastman** [comment]
Release created: https://github.com/pandegroup/pdbfixer/releases/tag/v1.3

**Comment by jchodera** [comment]
recipe in test: https://github.com/omnia-md/conda-recipes/pull/493

**Pull request merged**
