### PR TITLE
Eliminated most dependence on PdbStructure

### PR DESCRIPTION
**Pull request by peastman**
This simplifies the code, and also will make it easier to add support for loading PDBx files.  It requires the changes to Topology I just merged into OpenMM.

### CODE REVIEW

**Comment by peastman** [comment]
The build is failing because it isn't getting the latest changes to OpenMM.  Do I need to do something to fix that?

**Comment by kyleabeauchamp** [comment]
AFAIK, I don't think we have been building conda packages for every openmm commit--at least not successfully.  (https://binstar.org/omnia/openmm-dev  https://binstar.org/omnia/openmm)

That's something we could do if necessary, though.

**Comment by kyleabeauchamp** [comment]
Personally, I'm happy if you can confirm that tests run locally.

**Comment by rmcgibbo** [comment]
Travis is grabbing the conda package called `openmm`, which is the 6.2 release. https://github.com/pandegroup/pdbfixer/blob/master/.travis.yml#L15

**Comment by peastman** [comment]
I recall there being a lot of discussion about this issue for Omnia: how to handle development versions of projects that depend on development versions of other projects.  I don't remember what was decided though.

**Comment by kyleabeauchamp** [comment]
I think John has the jenkins infrastructure in place to do this.  AFAIK there are tests being run on every commit, it's just the packages aren't uploaded.  

Regarding "development versions"--you are correct, there's also the question of whether you want to run Travis against released packages or development packages.  IMHO, we are still using a temporary workaround (`xyz-dev`).  Whenever possible, IMHO I prefer to test against releases, but this is one of those cases where that's not feasible.

**Comment by rmcgibbo** [comment]
For some of the packages, the travis build, if it succeeds, pushes the package binary to as `<name_of_package>-dev` to binstar, but it doesn't look like OpenMM does this (successfully).

**Comment by jchodera** [comment]
Our current scheme is to use travis to push `<packagename>-dev` versions to the `omnia` binstar channel.  Downstream packages that use `<packagename>` then choose whether they have travis test against `<packagename>` (the latest stable release) or `<packagename>-dev` (the cutting-edge development version) on a package-by-package basis.

We should definitely fix the OpenMM travis to get `openmm-dev` pushed correctly on commits if that isn't working right now.

**Comment by peastman** [comment]
Looks like it will take a bit longer to get the conda issues resolved, so I'll just go ahead and merge this.  I ran the tests on my own computer and they all passed.

**Pull request merged**
