### PR TITLE
Fix broken doctest in applyMutations

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Seems to work on my machine, note the applyMutations line below.
```
Doctest: pdbfixer.pdbfixer.PDBFixer.__init__ ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.addMissingAtoms ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.addMissingHydrogens ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.addSolvent ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.applyMutations ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.findMissingAtoms ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.findMissingResidues ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.findNonstandardResidues ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.removeChains ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.removeHeterogens ... ok
Doctest: pdbfixer.pdbfixer.PDBFixer.replaceNonstandardResidues ... ok

----------------------------------------------------------------------
Ran 11 tests in 3.674s

OK
```

**Comment by jchodera** [comment]
Awesome!

**Comment by jchodera** [comment]
Looks like it passes!

Can this be merged, @peastman?

**Comment by peastman** [comment]
Thanks!

**Pull request merged**
