### PR TITLE
Py3

### PR DESCRIPTION
**Pull request by mpharrigan**
I had to make these changes to get pdbfixer to work with python 3. I also removed unnecessary imports from ui.py

### CODE REVIEW

**Comment by jchodera** [comment]
@peastman : Did you want to merge this before the `pdbfixer 1.1` release?  I think we're aiming for everything in omnia to be Python 3 compatible, aren't we?

**Comment by mpharrigan** [comment]
iirc there are still some bytes / unicode issues with fetching and displaying the images in py3 that this pr does not address

**Comment by kyleabeauchamp** [comment]
Hmm.  Given the py3k issues with yank, pymbar, and pdbfixer, we could always make omnia 1.0 a py27-only release and punt.

**Comment by mpharrigan** [comment]
I'd still recommend merging this. It lets pdbfixer at least function, although it isn't as pretty

**Comment by jchodera** [comment]
I think the py3 issues with yank, pdbfixer, and pymbar could be very
quickly addressed in a day.

**Comment by kyleabeauchamp** [comment]
Let's discuss on pymbar tracker.  For me, the issue is that we don't need to be investing a day backporting py3k compatibility into pymbar 2.2 when we're getting ready for a new major release where we already plan to have py3k compatibility.  We have ~tens of tasks that could "just take a day", and each one delays the omnia release further.

**Comment by jchodera** [comment]
Good point.

**Comment by jchodera** [comment]
@peastman: How about merging this?

**Comment by peastman** [comment]
Ok with me.  Is it ready to go?  The last I see in the discussion, there were still some problems that needed to be resolved.

**Comment by jchodera** [comment]
Good point.  At the very least, python 3.3 and 3.4 should be added to the `.travis.yml` build matrix in `env`, like this:
https://github.com/msmbuilder/msmbuilder/blob/master/.travis.yml#L20-L24

Also, it looks like travis integration has either switched off or the travis results are so old that they were deleted.  Can you check this, @peastman?

**Comment by mpharrigan** [comment]
It's confused because of the SimTk organization rename

**Comment by jchodera** [comment]
I'm guessing @peastman is the one that needs to fix that.

**Comment by jchodera** [comment]
@mpharrigan : Can you add this block to the `.travis.yml` in your PR?
```
env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.3
    - CONDA_PY=3.4
```
See, e.g.
https://github.com/msmbuilder/msmbuilder/blob/master/.travis.yml#L20-L24

**Comment by peastman** [comment]
Where is it that the name needs to be changed?

**Comment by mpharrigan** [comment]
I'll add that to the build matrix

I'm fixing the images as well

**Comment by jchodera** [comment]
@peastman: Perhaps you can just check the webhooks that are configured for this project and make sure Travis-CI is enabled?

**Comment by peastman** [comment]
It says it's enabled.

**Comment by mpharrigan** [comment]
I'd also like to humbly suggest using an extant web framework for future projects (e.g. http://www.tornadoweb.org) instead of rolling our own :)

**Comment by jchodera** [comment]
> I'd also like to humbly suggest using an extant web framework for future projects (e.g. http://www.tornadoweb.org) instead of rolling our own :)

PLEASE YES.

`tornado` is definitely on `conda`.

**Comment by jchodera** [comment]
All things pass on all Pythons!  Yay!

**Comment by mpharrigan** [comment]
This should be ready to merge

**Pull request merged**
